# Setup
title:               高级微观经济学
tagline:             ''
description:         '高级微观经济学'
url:                 https://yingzheng-econ.github.io/Advanced-Microeconomics/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ying Zheng
  url:
  email:             yingzheng@ruc.edu.cn

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-B19XHQTBSG
